#!/usr/bin/env bash
################
tmoe_zsh_02_main() {
	tmoe_zsh_02_env
	case "$1" in
	--h | -h | help | --help)
		cat <<-EOF
			参数
			local                                                                        --加载本地文件 Load local file
			ol 
			online                                                                       --加载在线文件 Load online file
			u                                                                            --更新(update tmoe-zsh)
			h                                                                            --get help info
			--tmoe_container_automatic_configure                                         --容器环境自动配置zsh
			p                                                                            -- 插件管理器 plugins manager
		EOF
		;;
	u | up | -u) source ${TMOE_ZSH_GIT_DIR}/zsh.sh -u ;;
	h | -h | --h | --help) source ${TMOE_ZSH_GIT_DIR}/zsh.sh -h ;;
	--tmoe_container_automatic_configure) source ${TMOE_ZSH_GIT_DIR}/zsh.sh --tmoe_container_automatic_configure ;;
	-p | plugin) source ${TMOE_ZSH_GIT_DIR}/zsh.sh -p ;;
	local) check_local_git_dir ;;
	ol | online) curl_tmoe_zsh_script_file ;;
	*) check_local_git_dir ;;
	esac
}
##############
tmoe_zsh_02_env() {
	case ${TMOE_ZSH_DIR} in
	"") TMOE_ZSH_DIR="${HOME}/.config/tmoe-zsh" ;;
	esac
	TMOE_ZSH_GIT_DIR="${TMOE_ZSH_DIR}/git"
	TMOE_ZSH_TOOL_DIR="${TMOE_ZSH_GIT_DIR}/tools"
	case ${ZSH_I_URL_02} in
	"") TMOE_ZSH_SCRIPT_URL='https://cdn.jsdelivr.net/gh/2moe/tmoe-zsh/zsh.sh' ;;
	*) TMOE_ZSH_SCRIPT_URL="${ZSH_I_URL_02}" ;;
	esac
}
###############
check_local_git_dir() {
	if [ -e "${TMOE_ZSH_GIT_DIR}/.git" ] && [ -s ${TMOE_ZSH_GIT_DIR}/zsh.sh ]; then
		source ${TMOE_ZSH_GIT_DIR}/zsh.sh
	else
		curl_tmoe_zsh_script_file
	fi
}
#############
curl_tmoe_zsh_script_file() {
	if [ $(command -v curl) ]; then
		bash -c "$(curl -LfsS ${TMOE_ZSH_SCRIPT_URL})"
	elif [ $(command -v wget) ]; then
		bash -c "$(wget -qO- ${TMOE_ZSH_SCRIPT_URL})"
	else
		bash -c "$(busybox wget --no-check-certificate -qO- ${TMOE_ZSH_SCRIPT_URL})"
	fi
}
################
tmoe_zsh_02_main "$@"
